- .travis.yml
- README.md
- scripts/gotest.sh
> Travis CI support

- .golangci.yml
- pkg/testutils/environment.go
- pkg/testutils/fixtures.go
- pkg/testutils/handlers.go
- pkg/v1/client.go
- pkg/v1/client_test.go
> Add testutils package and common service client

- .travis.yml
- pkg/testutils/fixtures.go
- pkg/testutils/handlers.go
- pkg/v1/client.go
- pkg/v1/client_test.go
- pkg/v1/domain/doc.go
- pkg/v1/domain/requests.go
- pkg/v1/domain/requests_opts.go
- pkg/v1/domain/schemas.go
- pkg/v1/domain/testing/fixtures.go
- pkg/v1/domain/testing/requests_test.go
- scripts/gotest.sh
> Domain v1: Add GetByID and GetByName functions

- pkg/v1/domain/doc.go
- pkg/v1/domain/requests.go
- pkg/v1/domain/testing/fixtures.go
- pkg/v1/domain/testing/requests_test.go
> Domain V1: Add List function

- pkg/v1/domain/doc.go
- pkg/v1/domain/requests.go
- pkg/v1/domain/requests_opts.go
- pkg/v1/domain/testing/fixtures.go
- pkg/v1/domain/testing/requests_test.go
> Domain V1: Add Create function

- pkg/v1/domain/requests.go
- pkg/v1/domain/testing/requests_test.go
> Domain V1: Add Delete function

- pkg/v1/domain/doc.go
> Add missing example usage for Delete method

- pkg/v1/client.go
- pkg/v1/domain/doc.go
- pkg/v1/domain/schemas.go
- pkg/v1/domain/testing/requests_test.go
- pkg/v1/record/doc.go
- pkg/v1/record/requests.go
- pkg/v1/record/requests_opts.go
- pkg/v1/record/schemas.go
- pkg/v1/record/testing/fixtures.go
- pkg/v1/record/testing/requests_test.go
> Record V1: Add Get function

- pkg/testutils/convert.go
- pkg/v1/record/doc.go
- pkg/v1/record/requests.go
- pkg/v1/record/schemas.go
- pkg/v1/record/testing/fixtures.go
- pkg/v1/record/testing/requests_test.go
> Record V1: ListByDomainID, ListByDomainName funcs

- pkg/v1/record/requests.go
List URL should end with trailing slash.
> Fix list records URL

- pkg/v1/record/requests.go
> Fix trailing slashes for records list requests

- pkg/v1/domain/doc.go
- pkg/v1/record/doc.go
- pkg/v1/record/requests.go
- pkg/v1/record/requests_opts.go
- pkg/v1/record/testing/fixtures.go
- pkg/v1/record/testing/requests_test.go
> Record V1: Add Create function

- pkg/v1/record/doc.go
- pkg/v1/record/requests.go
- pkg/v1/record/testing/requests_test.go
> Record V1: Add Delete function

- pkg/v1/record/doc.go
- pkg/v1/record/requests.go
- pkg/v1/record/requests_opts.go
- pkg/v1/record/testing/fixtures.go
- pkg/v1/record/testing/requests_test.go
> Record V1: Add Update function

- pkg/v1/client.go
- pkg/v1/client_test.go
> Extend error message with returned status code

- scripts/gotest.sh
This PR fixes gotest.sh, we should exit with status code based on failed tests.
> Fix gotest.sh

- .travis.yml
> Add go 1.15 in .travis.yaml

- go.mod
> Use Go 1.15 in go.mod

- pkg/v1/client.go
- pkg/v1/client_test.go
Add .WithOSToken() method to allow passing client token as X-Auth-Token to utilize keystone authorization.
> Add method to utilize token as openstack token

- README.md
- pkg/v2/rrsetManager.go
- pkg/v2/testing/rrsetManager_test.go
- pkg/v2/testing/test_utils.go
- pkg/v2/testing/zoneManager_test.go
- pkg/v2/zoneManager.go
Dns v2.
Rename uuid to id in rrset and zone. 
Rename zone to zone_id in rrset.
Fix tests.
Fix ReadMe example.
> DNSv2. Rename uuid to id in rrset and zone. Rename zone to zone_id in rrset.
